name: 'deploy'
description: ''

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash

    - run: echo $RANDOM
      shell: bash

    - uses: actions/checkout@v2

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Downloading an archive production artifacts
      uses: actions/download-artifact@v2
      with:
        path: dist

    #    - name: Install SSH Key
    #      uses: shimataro/ssh-key-action@v2
    #      with:
    #        key: ${{ secrets.SSH_PRIVATE_KEY }}
    #        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
