name: Continuous delivery

on:
  push:
    branches:
      - master

# permissions: read-all

env:
  # Секретные секретеры твоего приложение, (например подключение к базе данных, открытый API ключ и так далее).
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  BITRIX_API_KEY: ${{ secrets.BITRIX_API_KEY }}
  BITRIX_API_SECRET: ${{ secrets.BITRIX_API_SECRET }}

jobs:

  #  on-success:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #    steps:
  #      - run: echo "on-success on branch $GITHUB_REF"
  #
  #  on-failure:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #    steps:
  #      - run: echo "on-failure on branch $GITHUB_REF"

  #  staging:
  #    name: Staging deployment
  #    if: contains( github.ref, 'develop')
  #    # if: github.event.workflow_run.conclusion == 'success' && contains( github.ref, 'develop')
  #    # if: github.event_name == 'push'
  #    runs-on: ubuntu-latest
  #    timeout-minutes: 10
  #    environment:
  #      name: staging
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - uses: actions/deploy@v1

  prod:
    name: Production deployment
    if: contains( github.ref, 'master')
    # if: github.event.workflow_run.conclusion == 'success' && contains( github.ref, 'master')
    # if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: production
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: soprun/html5-boilerplate
          ref: v1.0.0
          # stored in GitHub secrets
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: ".github/actions/deploy/action.yml"

      — uses: "./.github/actions/deploy@master"
        with:
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
