name: Production Deployment

on:
  push:
    branches: [ master ]

jobs:
  prod:
    name: Production Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "Deploying to production server on branch ${GITHUB_REF}"
