name: Production Deployment

on:
  release:
    types: [ published ]
#  push:
#    branches:
#      - master
#    tags: # git tag -a v1.0.2
#      - "v*.*.*"

jobs:
  check:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"

  deploy:
    needs: check
    name: Production Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "Deploying to production server on branch $GITHUB_REF"
