name: Staging Deployment

on:
  push:
    branches: [ develop ]

jobs:
  check:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to staging server on branch $GITHUB_REF"

  stage:
    needs: [ build, check ]
    name: Staging Deployment
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v2
        env:
          NODE_ENV: production
        with:
          node-version: '14'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Run audit
        run: npm audit --production

      - name: Run npm-check-updates
        run: npm-check-updates --upgrade

      - run: echo "Deploying to stage server on branch ${GITHUB_REF}"
