name: CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Test
        run: npm test

#  on-success:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "on-success on branch $GITHUB_REF"
#
#      - name: The job has succeeded
#        if: ${{ success() }}
#
#  on-failure:
#    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "on-failure on branch $GITHUB_REF"
#      - name: The job has failed
#        if: ${{ failure() }}
#
#  prod-check:
#    if: ${{ github.ref == 'refs/heads/main' }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Deploying to production server on branch $GITHUB_REF"
#

#      - name: Run audit
#        run: npm run audit --production
#
#      - name: Run npm-check-updates
#        run: npm-check-updates --upgrade
#
#    - name: Archive code coverage results
#      uses: actions/upload-artifact@v2
#      with:
#        name: code-coverage-report
#        path: output/test/code-coverage.html
